name: Demo Workflow to test something...

on:
  push:
    branches: 
      - main

  repository_dispatch:
    types: [event1, event2]

  workflow_dispatch:
    inputs:
      ssd:
         description: 'The Solid State Drive on my Lappy'
         required: true
      logLevel:
        description: 'Log Level'
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tag:
        description: 'Apply a TAG after successful test run'
        required: true
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  StartJob:
    name: Run on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Running My Workflow"
          echo "Machine SSD: ${{ inputs.ssd }}"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "TAG source: ${{ inputs.tag }}"
          echo "Environment: ${{ inputs.environment }}"
        name: Workflow Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in a Repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

  job_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_3:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Job: ${{ github.job }}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - run: "echo Job: ${{ github.job }}"
      
